// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqotjboqyqgborcdfsol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb3RqYm9xeXFnYm9yY2Rmc29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MDIzMjIsImV4cCI6MjA1NDQ3ODMyMn0.LXhrtx3qcTPX-7VhHELzKlOn3L6w5f6If1cYfEpPRv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);